# .pre-commit-config.yaml file for https://github.com/zxdavb

# files: ^(ramses.*/.+)?[^/]+\.py$
exclude: ^examples/.*\.py$|^tests/_.*\.py$|^utils/.*\.py$|^\.secrets

repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args: ["--safe", "--quiet"]
        # files: ^(ramses.*/.+)?[^/]+\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - pydocstyle==6.1.1
        # files: ^ramses.*/.+\.py$
        # exclude: ^ramses.*/tests\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-check-blanket-type-ignore

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.931
  #   hooks:
  #   - id: mypy
  #     # files: ^ramses_rf/protocol/const.*\.py

  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: python
  #       types: [python]
