#
# https://docs.astral.sh/ruff/integrations/#github-actions

name: Linting via ruff

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    paths: ["src/**", "tests/**"]
  workflow_dispatch:


jobs:
  lint:  # name of job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1

      - run: echo "🍏 This job's status is ${{ job.status }}."
