# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# - see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing via pytest


on:
  push:
    branches: [ "master", "stable" ]
    paths: [
      ".github/workflows/check-test.yml",
      "src/**.py",
      "tests/**",
    ]

  pull_request:
    branches: [ "master", "stable" ]
    paths: [
      ".github/workflows/check-test.yml",
      "src/**.py",
      "tests/**",
    ]

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-sugar pytest-xdist PyYAML

      - name: Install the package
        run: pip install -e .

      - name: Test with pytest
        env:
          PYTEST_ADDOPTS: "--color=yes"
        run: pytest -v

      - run: echo "🍏 This job's status is ${{ job.status }}."
