#
# https://docs.astral.sh/ruff/integrations/#github-actions

name: Linting via ruff

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    paths: ["src/**", "tests/**"]
  workflow_dispatch:


jobs:
  lint:  # name of job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: chartboost/ruff-action@v1

      # Update output format to enable automatic inline annotations.
      - name: Check via ruff
        run: ruff check --output-format=github .

      - run: echo "🍏 This job's status is ${{ job.status }}."
